production:
adapter: postgresql
encoding: utf8
database: mariaaguilar
username: codeboxx
password: Codeboxx1!
host: codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com
port: 5432
pool: 10

development:
adapter: postgresql
encoding: utf8
database: mariaaguilar
username: codeboxx
password: Codeboxx1!
host: codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com
port: 5432
pool: 10